class ButtonValue:
    READ_RULES = 'Ознакомиться с правилами 🤓'
    DONT_READ_RULES = 'Я не буду читать правила 😐'
    AGREE_WITH_RULES = 'Я согласен с правилами 😎'
    DONT_AGREE_WITH_RULES = 'Я не согласен с правилами 🤔'
    MALE_GENDER = 'Мужской 👨'
    FEMALE_GENDER = 'Женский 👩‍🦰'
    WANT_UPLOAD_PHOTO = 'Да! Хочу загрузить свою фоточку 😎'
    DONT_WANT_UPLOAD_PHOTO = 'Нет, не буду загружать свое фото 🙂'
    YES = 'Да ✅'
    NO = 'Нет ❌'
    CHECK_ACCESS = 'Проверить состояние анкеты ✅'
