from .start import dp
from .callbacks_for_pagination import dp
from .moders_output import dp
from .show_card import dp
from .show_department_cards import dp
from .department_handler import dp
from .project_handler import dp
from .rules import dp
from .help import dp
